GET http://localhost:3001/todos
###
POST  http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "build a Mern stack "
}

###
DELETE http://localhost:3001/todo/delete/6624bb5241219c84348d4598
###
PUT http://localhost:3001/todo/complete/6624bb5241219c84348d4598